package br.com.diegosilva.lotericas.core.api.parser;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import br.com.diegosilva.lotericas.core.api.rpc.*;
import br.com.diegosilva.lotericas.core.api.base.*;

public class RpcParser extends BaseParser<RpcScope> {
    @Override
    public RpcScope read(int type, byte[] payload) throws IOException {
        switch(type) {
            case 18: return RequestLoadGroupsPre.fromBytes(payload);
            case 19: return RequestCreateGroupPre.fromBytes(payload);
            case 20: return ResponseLoadGroupsPre.fromBytes(payload);
            case 21: return ResponseCreateGroupPre.fromBytes(payload);
        }
        throw new IOException();
    }
}
