package br.com.diegosilva.lotericas.core.api.parser;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import br.com.diegosilva.lotericas.core.api.base.*;
import br.com.diegosilva.lotericas.core.api.rpc.*;

import static im.actor.runtime.bser.Utils.*;

public class RpcParser extends BaseParser<RpcScope> {
    @Override
    public RpcScope read(int type, byte[] payload) throws IOException {
        switch (type) {
            case 18:
                return RequestLoadGroupsPre.fromBytes(payload);
            case 19:
                return RequestCreateGroupPre.fromBytes(payload);
            case 20:
                return ResponseLoadGroupsPre.fromBytes(payload);
            case 21:
                return ResponseCreateGroupPre.fromBytes(payload);
        }
        throw new IOException();
    }
}
