#!/usr/bin/env bash

./gradlew :actor-sdk:sdk-core:core:core-js:buildPackage

echo "Build Finished, copying builded file"

cp actor-sdk/sdk-core/core/core-js/build/package/actor.nocache.js ActorSDK-Web/node_modules/actor-js/actor.js

echo "------ File Copied -----"
