package br.com.diegosilva.lotericas.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;

public class ApiGroupPre extends BserObject {

    private long groupId;
    private long groupFatherId;
    private List<ApiGroupPre> childrens;

    public ApiGroupPre(long groupId, long groupFatherId, @NotNull List<ApiGroupPre> childrens) {
        this.groupId = groupId;
        this.groupFatherId = groupFatherId;
        this.childrens = childrens;
    }

    public ApiGroupPre() {

    }

    public long getGroupId() {
        return this.groupId;
    }

    public long getGroupFatherId() {
        return this.groupFatherId;
    }

    @NotNull
    public List<ApiGroupPre> getChildrens() {
        return this.childrens;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupId = values.getLong(1);
        this.groupFatherId = values.getLong(2);
        List<ApiGroupPre> _childrens = new ArrayList<ApiGroupPre>();
        for (int i = 0; i < values.getRepeatedCount(5); i ++) {
            _childrens.add(new ApiGroupPre());
        }
        this.childrens = values.getRepeatedObj(5, _childrens);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.groupId);
        writer.writeLong(2, this.groupFatherId);
        writer.writeRepeatedObj(5, this.childrens);
    }

    @Override
    public String toString() {
        String res = "struct GroupPre{";
        res += "}";
        return res;
    }

}
