package br.com.diegosilva.lotericas.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import static im.actor.runtime.bser.Utils.*;

public final class ApiVersion {

    public static final String VERSION = "0.1";

    public static final int VERSION_MAJOR = 0;
    public static final int VERSION_MINOR = 1;

    private ApiVersion() {
    }
}
