package br.com.diegosilva.lotericas.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import br.com.diegosilva.lotericas.core.api.*;

public class RequestLoadGroupsPre extends Request<ResponseLoadGroupsPre> {

    public static final int HEADER = 0x12;
    public static RequestLoadGroupsPre fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestLoadGroupsPre(), data);
    }


    public RequestLoadGroupsPre() {

    }

    @Override
    public void parse(BserValues values) throws IOException {
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
    }

    @Override
    public String toString() {
        String res = "rpc LoadGroupsPre{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
