package br.com.diegosilva.lotericas.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import br.com.diegosilva.lotericas.core.api.*;

import static im.actor.runtime.bser.Utils.*;

public class RequestLoadGroupsPre extends Request<ResponseLoadGroupsPre> {

    public static final int HEADER = 0x12;

    public static RequestLoadGroupsPre fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestLoadGroupsPre(), data);
    }


    public RequestLoadGroupsPre() {

    }

    @Override
    public void parse(BserValues values) throws IOException {
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
    }

    @Override
    public String toString() {
        String res = "rpc LoadGroupsPre{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
