package br.com.diegosilva.lotericas.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import br.com.diegosilva.lotericas.core.api.*;

import static im.actor.runtime.bser.Utils.*;

public class ResponseCreateGroupPre extends Response {

    public static final int HEADER = 0x15;

    public static ResponseCreateGroupPre fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseCreateGroupPre(), data);
    }

    private int seq;
    private byte[] state;
    private ApiGroupPre groupPre;

    public ResponseCreateGroupPre(int seq, @NotNull byte[] state, @NotNull ApiGroupPre groupPre) {
        this.seq = seq;
        this.state = state;
        this.groupPre = groupPre;
    }

    public ResponseCreateGroupPre() {

    }

    public int getSeq() {
        return this.seq;
    }

    @NotNull
    public byte[] getState() {
        return this.state;
    }

    @NotNull
    public ApiGroupPre getGroupPre() {
        return this.groupPre;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.seq = values.getInt(1);
        this.state = values.getBytes(2);
        this.groupPre = values.getObj(3, new ApiGroupPre());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.seq);
        if (this.state == null) {
            throw new IOException();
        }
        writer.writeBytes(2, this.state);
        if (this.groupPre == null) {
            throw new IOException();
        }
        writer.writeObject(3, this.groupPre);
    }

    @Override
    public String toString() {
        String res = "tuple CreateGroupPre{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
