package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import im.actor.core.api.ApiGroupOutPeer;
import im.actor.core.api.ApiUpdateOptimization;
import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestEditGroupTitle extends Request<ResponseSeqDate> {

    public static final int HEADER = 0x55;

    public static RequestEditGroupTitle fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestEditGroupTitle(), data);
    }

    private ApiGroupOutPeer groupPeer;
    private long rid;
    private String title;
    private List<ApiUpdateOptimization> optimizations;

    public RequestEditGroupTitle(@NotNull ApiGroupOutPeer groupPeer, long rid, @NotNull String title, @NotNull List<ApiUpdateOptimization> optimizations) {
        this.groupPeer = groupPeer;
        this.rid = rid;
        this.title = title;
        this.optimizations = optimizations;
    }

    public RequestEditGroupTitle() {

    }

    @NotNull
    public ApiGroupOutPeer getGroupPeer() {
        return this.groupPeer;
    }

    public long getRid() {
        return this.rid;
    }

    @NotNull
    public String getTitle() {
        return this.title;
    }

    @NotNull
    public List<ApiUpdateOptimization> getOptimizations() {
        return this.optimizations;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupPeer = values.getObj(1, new ApiGroupOutPeer());
        this.rid = values.getLong(4);
        this.title = values.getString(3);
        this.optimizations = new ArrayList<ApiUpdateOptimization>();
        for (int b : values.getRepeatedInt(5)) {
            optimizations.add(ApiUpdateOptimization.parse(b));
        }
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.groupPeer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.groupPeer);
        writer.writeLong(4, this.rid);
        if (this.title == null) {
            throw new IOException();
        }
        writer.writeString(3, this.title);
        for (ApiUpdateOptimization i : this.optimizations) {
            writer.writeInt(5, i.getValue());
        }
    }

    @Override
    public String toString() {
        String res = "rpc EditGroupTitle{";
        res += "groupPeer=" + this.groupPeer;
        res += ", rid=" + this.rid;
        res += ", title=" + this.title;
        res += ", optimizations=" + this.optimizations;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
