package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.Nullable;

import java.io.IOException;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestLoadGroupsPre extends Request<ResponseLoadGroupsPre> {

    public static final int HEADER = 0x17;
    public static RequestLoadGroupsPre fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestLoadGroupsPre(), data);
    }

    private Integer idParent;

    public RequestLoadGroupsPre(@Nullable Integer idParent) {
        this.idParent = idParent;
    }

    public RequestLoadGroupsPre() {

    }

    @Nullable
    public Integer getIdParent() {
        return this.idParent;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.idParent = values.optInt(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.idParent != null) {
            writer.writeInt(1, this.idParent);
        }
    }

    @Override
    public String toString() {
        String res = "rpc LoadGroupsPre{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
