package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiGroupOutPeer;
import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestJoinGroupByPeer extends Request<ResponseSeq> {

    public static final int HEADER = 0xaa2;

    public static RequestJoinGroupByPeer fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestJoinGroupByPeer(), data);
    }

    private ApiGroupOutPeer groupPeer;

    public RequestJoinGroupByPeer(@NotNull ApiGroupOutPeer groupPeer) {
        this.groupPeer = groupPeer;
    }

    public RequestJoinGroupByPeer() {

    }

    @NotNull
    public ApiGroupOutPeer getGroupPeer() {
        return this.groupPeer;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupPeer = values.getObj(1, new ApiGroupOutPeer());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.groupPeer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.groupPeer);
    }

    @Override
    public String toString() {
        String res = "rpc JoinGroupByPeer{";
        res += "groupPeer=" + this.groupPeer;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
