package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestSendCodeByPhoneCall extends Request<ResponseVoid> {

    public static final int HEADER = 0xc5;

    public static RequestSendCodeByPhoneCall fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestSendCodeByPhoneCall(), data);
    }

    private String transactionHash;

    public RequestSendCodeByPhoneCall(@NotNull String transactionHash) {
        this.transactionHash = transactionHash;
    }

    public RequestSendCodeByPhoneCall() {

    }

    @NotNull
    public String getTransactionHash() {
        return this.transactionHash;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.transactionHash = values.getString(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.transactionHash == null) {
            throw new IOException();
        }
        writer.writeString(1, this.transactionHash);
    }

    @Override
    public String toString() {
        String res = "rpc SendCodeByPhoneCall{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
