package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import im.actor.core.api.ApiGroupOutPeer;
import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestLoadFullGroups extends Request<ResponseLoadFullGroups> {

    public static final int HEADER = 0xade;

    public static RequestLoadFullGroups fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestLoadFullGroups(), data);
    }

    private List<ApiGroupOutPeer> groups;

    public RequestLoadFullGroups(@NotNull List<ApiGroupOutPeer> groups) {
        this.groups = groups;
    }

    public RequestLoadFullGroups() {

    }

    @NotNull
    public List<ApiGroupOutPeer> getGroups() {
        return this.groups;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        List<ApiGroupOutPeer> _groups = new ArrayList<ApiGroupOutPeer>();
        for (int i = 0; i < values.getRepeatedCount(1); i++) {
            _groups.add(new ApiGroupOutPeer());
        }
        this.groups = values.getRepeatedObj(1, _groups);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRepeatedObj(1, this.groups);
    }

    @Override
    public String toString() {
        String res = "rpc LoadFullGroups{";
        res += "groups=" + this.groups.size();
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
