package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import im.actor.core.api.ApiGroupOutPeer;
import im.actor.core.api.ApiUpdateOptimization;
import im.actor.core.api.ApiUserOutPeer;
import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestKickUser extends Request<ResponseSeqDate> {

    public static final int HEADER = 0x47;

    public static RequestKickUser fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestKickUser(), data);
    }

    private ApiGroupOutPeer groupPeer;
    private long rid;
    private ApiUserOutPeer user;
    private List<ApiUpdateOptimization> optimizations;

    public RequestKickUser(@NotNull ApiGroupOutPeer groupPeer, long rid, @NotNull ApiUserOutPeer user, @NotNull List<ApiUpdateOptimization> optimizations) {
        this.groupPeer = groupPeer;
        this.rid = rid;
        this.user = user;
        this.optimizations = optimizations;
    }

    public RequestKickUser() {

    }

    @NotNull
    public ApiGroupOutPeer getGroupPeer() {
        return this.groupPeer;
    }

    public long getRid() {
        return this.rid;
    }

    @NotNull
    public ApiUserOutPeer getUser() {
        return this.user;
    }

    @NotNull
    public List<ApiUpdateOptimization> getOptimizations() {
        return this.optimizations;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupPeer = values.getObj(1, new ApiGroupOutPeer());
        this.rid = values.getLong(4);
        this.user = values.getObj(3, new ApiUserOutPeer());
        this.optimizations = new ArrayList<ApiUpdateOptimization>();
        for (int b : values.getRepeatedInt(5)) {
            optimizations.add(ApiUpdateOptimization.parse(b));
        }
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.groupPeer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.groupPeer);
        writer.writeLong(4, this.rid);
        if (this.user == null) {
            throw new IOException();
        }
        writer.writeObject(3, this.user);
        for (ApiUpdateOptimization i : this.optimizations) {
            writer.writeInt(5, i.getValue());
        }
    }

    @Override
    public String toString() {
        String res = "rpc KickUser{";
        res += "groupPeer=" + this.groupPeer;
        res += ", rid=" + this.rid;
        res += ", user=" + this.user;
        res += ", optimizations=" + this.optimizations;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
