package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import im.actor.core.api.ApiUpdateOptimization;
import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestLoadGroupedDialogs extends Request<ResponseLoadGroupedDialogs> {

    public static final int HEADER = 0xe1;

    public static RequestLoadGroupedDialogs fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestLoadGroupedDialogs(), data);
    }

    private List<ApiUpdateOptimization> optimizations;

    public RequestLoadGroupedDialogs(@NotNull List<ApiUpdateOptimization> optimizations) {
        this.optimizations = optimizations;
    }

    public RequestLoadGroupedDialogs() {

    }

    @NotNull
    public List<ApiUpdateOptimization> getOptimizations() {
        return this.optimizations;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.optimizations = new ArrayList<ApiUpdateOptimization>();
        for (int b : values.getRepeatedInt(1)) {
            optimizations.add(ApiUpdateOptimization.parse(b));
        }
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        for (ApiUpdateOptimization i : this.optimizations) {
            writer.writeInt(1, i.getValue());
        }
    }

    @Override
    public String toString() {
        String res = "rpc LoadGroupedDialogs{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
