package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiUserOutPeer;
import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestUnblockUser extends Request<ResponseSeq> {

    public static final int HEADER = 0xa4d;

    public static RequestUnblockUser fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestUnblockUser(), data);
    }

    private ApiUserOutPeer peer;

    public RequestUnblockUser(@NotNull ApiUserOutPeer peer) {
        this.peer = peer;
    }

    public RequestUnblockUser() {

    }

    @NotNull
    public ApiUserOutPeer getPeer() {
        return this.peer;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.peer = values.getObj(1, new ApiUserOutPeer());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.peer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.peer);
    }

    @Override
    public String toString() {
        String res = "rpc UnblockUser{";
        res += "peer=" + this.peer;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
