package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import im.actor.core.api.*;

public class RequestLoadGroups extends Request<ResponseLoadGroups> {

    public static final int HEADER = 0x251;
    public static RequestLoadGroups fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestLoadGroups(), data);
    }

    private List<ApiGroupOutPeer> groups;

    public RequestLoadGroups(@NotNull List<ApiGroupOutPeer> groups) {
        this.groups = groups;
    }

    public RequestLoadGroups() {

    }

    @NotNull
    public List<ApiGroupOutPeer> getGroups() {
        return this.groups;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        List<ApiGroupOutPeer> _groups = new ArrayList<ApiGroupOutPeer>();
        for (int i = 0; i < values.getRepeatedCount(1); i ++) {
            _groups.add(new ApiGroupOutPeer());
        }
        this.groups = values.getRepeatedObj(1, _groups);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRepeatedObj(1, this.groups);
    }

    @Override
    public String toString() {
        String res = "rpc LoadGroups{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
