package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestRegisterApplePushKit extends Request<ResponseVoid> {

    public static final int HEADER = 0xa10;

    public static RequestRegisterApplePushKit fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestRegisterApplePushKit(), data);
    }

    private int apnsKey;
    private String token;

    public RequestRegisterApplePushKit(int apnsKey, @NotNull String token) {
        this.apnsKey = apnsKey;
        this.token = token;
    }

    public RequestRegisterApplePushKit() {

    }

    public int getApnsKey() {
        return this.apnsKey;
    }

    @NotNull
    public String getToken() {
        return this.token;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.apnsKey = values.getInt(1);
        this.token = values.getString(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.apnsKey);
        if (this.token == null) {
            throw new IOException();
        }
        writer.writeString(2, this.token);
    }

    @Override
    public String toString() {
        String res = "rpc RegisterApplePushKit{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
