package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import im.actor.core.api.*;

public class RequestLoadDocsHistory extends Request<ResponseLoadDocsHistory> {

    public static final int HEADER = 0x106;
    public static RequestLoadDocsHistory fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestLoadDocsHistory(), data);
    }

    private ApiOutPeer peer;
    private long date;
    private ApiListLoadMode loadMode;
    private int limit;
    private ApiDocsHistoryType docType;

    public RequestLoadDocsHistory(@NotNull ApiOutPeer peer, long date, @Nullable ApiListLoadMode loadMode, int limit, @NotNull ApiDocsHistoryType docType) {
        this.peer = peer;
        this.date = date;
        this.loadMode = loadMode;
        this.limit = limit;
        this.docType = docType;
    }

    public RequestLoadDocsHistory() {

    }

    @NotNull
    public ApiOutPeer getPeer() {
        return this.peer;
    }

    public long getDate() {
        return this.date;
    }

    @Nullable
    public ApiListLoadMode getLoadMode() {
        return this.loadMode;
    }

    public int getLimit() {
        return this.limit;
    }

    @NotNull
    public ApiDocsHistoryType getDocType() {
        return this.docType;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.peer = values.getObj(1, new ApiOutPeer());
        this.date = values.getLong(3);
        int val_loadMode = values.getInt(4, 0);
        if (val_loadMode != 0) {
            this.loadMode = ApiListLoadMode.parse(val_loadMode);
        }
        this.limit = values.getInt(5);
        this.docType = ApiDocsHistoryType.parse(values.getInt(6));
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.peer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.peer);
        writer.writeLong(3, this.date);
        if (this.loadMode != null) {
            writer.writeInt(4, this.loadMode.getValue());
        }
        writer.writeInt(5, this.limit);
        if (this.docType == null) {
            throw new IOException();
        }
        writer.writeInt(6, this.docType.getValue());
    }

    @Override
    public String toString() {
        String res = "rpc LoadDocsHistory{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
