package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiOutPeer;
import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestShowDialog extends Request<ResponseDialogsOrder> {

    public static final int HEADER = 0xe8;

    public static RequestShowDialog fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestShowDialog(), data);
    }

    private ApiOutPeer peer;

    public RequestShowDialog(@NotNull ApiOutPeer peer) {
        this.peer = peer;
    }

    public RequestShowDialog() {

    }

    @NotNull
    public ApiOutPeer getPeer() {
        return this.peer;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.peer = values.getObj(1, new ApiOutPeer());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.peer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.peer);
    }

    @Override
    public String toString() {
        String res = "rpc ShowDialog{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
