package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiGroupOutPeer;
import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestEnterGroupObsolete extends Request<ResponseEnterGroupObsolete> {

    public static final int HEADER = 0xc7;

    public static RequestEnterGroupObsolete fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestEnterGroupObsolete(), data);
    }

    private ApiGroupOutPeer peer;

    public RequestEnterGroupObsolete(@NotNull ApiGroupOutPeer peer) {
        this.peer = peer;
    }

    public RequestEnterGroupObsolete() {

    }

    @NotNull
    public ApiGroupOutPeer getPeer() {
        return this.peer;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.peer = values.getObj(1, new ApiGroupOutPeer());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.peer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.peer);
    }

    @Override
    public String toString() {
        String res = "rpc EnterGroupObsolete{";
        res += "peer=" + this.peer;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
