package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestGetFileUploadUrl extends Request<ResponseGetFileUploadUrl> {

    public static final int HEADER = 0x61;

    public static RequestGetFileUploadUrl fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestGetFileUploadUrl(), data);
    }

    private int expectedSize;

    public RequestGetFileUploadUrl(int expectedSize) {
        this.expectedSize = expectedSize;
    }

    public RequestGetFileUploadUrl() {

    }

    public int getExpectedSize() {
        return this.expectedSize;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.expectedSize = values.getInt(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.expectedSize);
    }

    @Override
    public String toString() {
        String res = "rpc GetFileUploadUrl{";
        res += "expectedSize=" + this.expectedSize;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
