package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestEditMyTimeZone extends Request<ResponseSeq> {

    public static final int HEADER = 0x90;

    public static RequestEditMyTimeZone fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestEditMyTimeZone(), data);
    }

    private String tz;

    public RequestEditMyTimeZone(@NotNull String tz) {
        this.tz = tz;
    }

    public RequestEditMyTimeZone() {

    }

    @NotNull
    public String getTz() {
        return this.tz;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.tz = values.getString(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.tz == null) {
            throw new IOException();
        }
        writer.writeString(1, this.tz);
    }

    @Override
    public String toString() {
        String res = "rpc EditMyTimeZone{";
        res += "tz=" + this.tz;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
