package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestCheckNickName extends Request<ResponseBool> {

    public static final int HEADER = 0xce;

    public static RequestCheckNickName fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestCheckNickName(), data);
    }

    private String nickname;

    public RequestCheckNickName(@NotNull String nickname) {
        this.nickname = nickname;
    }

    public RequestCheckNickName() {

    }

    @NotNull
    public String getNickname() {
        return this.nickname;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.nickname = values.getString(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.nickname == null) {
            throw new IOException();
        }
        writer.writeString(1, this.nickname);
    }

    @Override
    public String toString() {
        String res = "rpc CheckNickName{";
        res += "nickname=" + this.nickname;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
