package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestUnregisterApplePushKit extends Request<ResponseVoid> {

    public static final int HEADER = 0xa49;

    public static RequestUnregisterApplePushKit fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestUnregisterApplePushKit(), data);
    }

    private String token;

    public RequestUnregisterApplePushKit(@NotNull String token) {
        this.token = token;
    }

    public RequestUnregisterApplePushKit() {

    }

    @NotNull
    public String getToken() {
        return this.token;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.token = values.getString(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.token == null) {
            throw new IOException();
        }
        writer.writeString(1, this.token);
    }

    @Override
    public String toString() {
        String res = "rpc UnregisterApplePushKit{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
