package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestUnregisterActorPush extends Request<ResponseVoid> {

    public static final int HEADER = 0xa4b;

    public static RequestUnregisterActorPush fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestUnregisterActorPush(), data);
    }

    private String endpoint;

    public RequestUnregisterActorPush(@NotNull String endpoint) {
        this.endpoint = endpoint;
    }

    public RequestUnregisterActorPush() {

    }

    @NotNull
    public String getEndpoint() {
        return this.endpoint;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.endpoint = values.getString(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.endpoint == null) {
            throw new IOException();
        }
        writer.writeString(1, this.endpoint);
    }

    @Override
    public String toString() {
        String res = "rpc UnregisterActorPush{";
        res += "endpoint=" + this.endpoint;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
