package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiAdminSettings;
import im.actor.core.api.ApiGroupOutPeer;
import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestSaveAdminSettings extends Request<ResponseVoid> {

    public static final int HEADER = 0xae8;

    public static RequestSaveAdminSettings fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestSaveAdminSettings(), data);
    }

    private ApiGroupOutPeer groupPeer;
    private ApiAdminSettings settings;

    public RequestSaveAdminSettings(@NotNull ApiGroupOutPeer groupPeer, @NotNull ApiAdminSettings settings) {
        this.groupPeer = groupPeer;
        this.settings = settings;
    }

    public RequestSaveAdminSettings() {

    }

    @NotNull
    public ApiGroupOutPeer getGroupPeer() {
        return this.groupPeer;
    }

    @NotNull
    public ApiAdminSettings getSettings() {
        return this.settings;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupPeer = values.getObj(1, new ApiGroupOutPeer());
        this.settings = values.getObj(2, new ApiAdminSettings());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.groupPeer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.groupPeer);
        if (this.settings == null) {
            throw new IOException();
        }
        writer.writeObject(2, this.settings);
    }

    @Override
    public String toString() {
        String res = "rpc SaveAdminSettings{";
        res += "groupPeer=" + this.groupPeer;
        res += ", settings=" + this.settings;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
