package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiOutTeam;
import im.actor.core.api.ApiUserOutPeer;
import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestInviteToTeam extends Request<ResponseVoid> {

    public static final int HEADER = 0xa08;

    public static RequestInviteToTeam fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestInviteToTeam(), data);
    }

    private ApiUserOutPeer user;
    private ApiOutTeam destTeam;

    public RequestInviteToTeam(@NotNull ApiUserOutPeer user, @NotNull ApiOutTeam destTeam) {
        this.user = user;
        this.destTeam = destTeam;
    }

    public RequestInviteToTeam() {

    }

    @NotNull
    public ApiUserOutPeer getUser() {
        return this.user;
    }

    @NotNull
    public ApiOutTeam getDestTeam() {
        return this.destTeam;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.user = values.getObj(1, new ApiUserOutPeer());
        this.destTeam = values.getObj(3, new ApiOutTeam());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.user == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.user);
        if (this.destTeam == null) {
            throw new IOException();
        }
        writer.writeObject(3, this.destTeam);
    }

    @Override
    public String toString() {
        String res = "rpc InviteToTeam{";
        res += "user=" + this.user;
        res += ", destTeam=" + this.destTeam;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
