package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.List;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestEditMyPreferredLanguages extends Request<ResponseSeq> {

    public static final int HEADER = 0x91;

    public static RequestEditMyPreferredLanguages fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestEditMyPreferredLanguages(), data);
    }

    private List<String> preferredLanguages;

    public RequestEditMyPreferredLanguages(@NotNull List<String> preferredLanguages) {
        this.preferredLanguages = preferredLanguages;
    }

    public RequestEditMyPreferredLanguages() {

    }

    @NotNull
    public List<String> getPreferredLanguages() {
        return this.preferredLanguages;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.preferredLanguages = values.getRepeatedString(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRepeatedString(1, this.preferredLanguages);
    }

    @Override
    public String toString() {
        String res = "rpc EditMyPreferredLanguages{";
        res += "preferredLanguages=" + this.preferredLanguages;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
