package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiFileLocation;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseCommitFileUpload extends Response {

    public static final int HEADER = 0x8a;

    public static ResponseCommitFileUpload fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseCommitFileUpload(), data);
    }

    private ApiFileLocation uploadedFileLocation;

    public ResponseCommitFileUpload(@NotNull ApiFileLocation uploadedFileLocation) {
        this.uploadedFileLocation = uploadedFileLocation;
    }

    public ResponseCommitFileUpload() {

    }

    @NotNull
    public ApiFileLocation getUploadedFileLocation() {
        return this.uploadedFileLocation;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.uploadedFileLocation = values.getObj(1, new ApiFileLocation());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.uploadedFileLocation == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.uploadedFileLocation);
    }

    @Override
    public String toString() {
        String res = "tuple CommitFileUpload{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
