package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import im.actor.core.api.ApiGroupFull;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseLoadFullGroups extends Response {

    public static final int HEADER = 0xadf;

    public static ResponseLoadFullGroups fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseLoadFullGroups(), data);
    }

    private List<ApiGroupFull> groups;

    public ResponseLoadFullGroups(@NotNull List<ApiGroupFull> groups) {
        this.groups = groups;
    }

    public ResponseLoadFullGroups() {

    }

    @NotNull
    public List<ApiGroupFull> getGroups() {
        return this.groups;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        List<ApiGroupFull> _groups = new ArrayList<ApiGroupFull>();
        for (int i = 0; i < values.getRepeatedCount(1); i++) {
            _groups.add(new ApiGroupFull());
        }
        this.groups = values.getRepeatedObj(1, _groups);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRepeatedObj(1, this.groups);
    }

    @Override
    public String toString() {
        String res = "tuple LoadFullGroups{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
