package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import im.actor.core.api.ApiUser;
import im.actor.core.api.ApiUserOutPeer;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseSearchContacts extends Response {

    public static final int HEADER = 0x71;

    public static ResponseSearchContacts fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseSearchContacts(), data);
    }

    private List<ApiUser> users;
    private List<ApiUserOutPeer> userPeers;

    public ResponseSearchContacts(@NotNull List<ApiUser> users, @NotNull List<ApiUserOutPeer> userPeers) {
        this.users = users;
        this.userPeers = userPeers;
    }

    public ResponseSearchContacts() {

    }

    @NotNull
    public List<ApiUser> getUsers() {
        return this.users;
    }

    @NotNull
    public List<ApiUserOutPeer> getUserPeers() {
        return this.userPeers;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        List<ApiUser> _users = new ArrayList<ApiUser>();
        for (int i = 0; i < values.getRepeatedCount(1); i++) {
            _users.add(new ApiUser());
        }
        this.users = values.getRepeatedObj(1, _users);
        List<ApiUserOutPeer> _userPeers = new ArrayList<ApiUserOutPeer>();
        for (int i = 0; i < values.getRepeatedCount(2); i++) {
            _userPeers.add(new ApiUserOutPeer());
        }
        this.userPeers = values.getRepeatedObj(2, _userPeers);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRepeatedObj(1, this.users);
        writer.writeRepeatedObj(2, this.userPeers);
    }

    @Override
    public String toString() {
        String res = "tuple SearchContacts{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
