package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import im.actor.core.api.*;

public class ResponseCreateSurvey extends Response {

    public static final int HEADER = 0x502;
    public static ResponseCreateSurvey fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseCreateSurvey(), data);
    }

    private int seq;
    private byte[] state;
    private List<ApiUser> relatedUsers;
    private List<ApiGroup> relatedGroups;

    public ResponseCreateSurvey(int seq, @NotNull byte[] state, @NotNull List<ApiUser> relatedUsers, @NotNull List<ApiGroup> relatedGroups) {
        this.seq = seq;
        this.state = state;
        this.relatedUsers = relatedUsers;
        this.relatedGroups = relatedGroups;
    }

    public ResponseCreateSurvey() {

    }

    public int getSeq() {
        return this.seq;
    }

    @NotNull
    public byte[] getState() {
        return this.state;
    }

    @NotNull
    public List<ApiUser> getRelatedUsers() {
        return this.relatedUsers;
    }

    @NotNull
    public List<ApiGroup> getRelatedGroups() {
        return this.relatedGroups;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.seq = values.getInt(1);
        this.state = values.getBytes(2);
        List<ApiUser> _relatedUsers = new ArrayList<ApiUser>();
        for (int i = 0; i < values.getRepeatedCount(3); i ++) {
            _relatedUsers.add(new ApiUser());
        }
        this.relatedUsers = values.getRepeatedObj(3, _relatedUsers);
        List<ApiGroup> _relatedGroups = new ArrayList<ApiGroup>();
        for (int i = 0; i < values.getRepeatedCount(4); i ++) {
            _relatedGroups.add(new ApiGroup());
        }
        this.relatedGroups = values.getRepeatedObj(4, _relatedGroups);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.seq);
        if (this.state == null) {
            throw new IOException();
        }
        writer.writeBytes(2, this.state);
        writer.writeRepeatedObj(3, this.relatedUsers);
        writer.writeRepeatedObj(4, this.relatedGroups);
    }

    @Override
    public String toString() {
        String res = "tuple CreateSurvey{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
