package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseReJoinEventBus extends Response {

    public static final int HEADER = 0xa74;

    public static ResponseReJoinEventBus fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseReJoinEventBus(), data);
    }

    private long deviceId;

    public ResponseReJoinEventBus(long deviceId) {
        this.deviceId = deviceId;
    }

    public ResponseReJoinEventBus() {

    }

    public long getDeviceId() {
        return this.deviceId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.deviceId = values.getLong(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.deviceId);
    }

    @Override
    public String toString() {
        String res = "tuple ReJoinEventBus{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
