package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiEmailActivationType;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseStartEmailAuth extends Response {

    public static final int HEADER = 0xba;

    public static ResponseStartEmailAuth fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseStartEmailAuth(), data);
    }

    private String transactionHash;
    private boolean isRegistered;
    private ApiEmailActivationType activationType;

    public ResponseStartEmailAuth(@NotNull String transactionHash, boolean isRegistered, @NotNull ApiEmailActivationType activationType) {
        this.transactionHash = transactionHash;
        this.isRegistered = isRegistered;
        this.activationType = activationType;
    }

    public ResponseStartEmailAuth() {

    }

    @NotNull
    public String getTransactionHash() {
        return this.transactionHash;
    }

    public boolean isRegistered() {
        return this.isRegistered;
    }

    @NotNull
    public ApiEmailActivationType getActivationType() {
        return this.activationType;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.transactionHash = values.getString(1);
        this.isRegistered = values.getBool(2);
        this.activationType = ApiEmailActivationType.parse(values.getInt(3));
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.transactionHash == null) {
            throw new IOException();
        }
        writer.writeString(1, this.transactionHash);
        writer.writeBool(2, this.isRegistered);
        if (this.activationType == null) {
            throw new IOException();
        }
        writer.writeInt(3, this.activationType.getValue());
    }

    @Override
    public String toString() {
        String res = "tuple StartEmailAuth{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
