package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import im.actor.core.api.ApiTeam;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseTeamsList extends Response {

    public static final int HEADER = 0xa02;

    public static ResponseTeamsList fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseTeamsList(), data);
    }

    private List<ApiTeam> teams;

    public ResponseTeamsList(@NotNull List<ApiTeam> teams) {
        this.teams = teams;
    }

    public ResponseTeamsList() {

    }

    @NotNull
    public List<ApiTeam> getTeams() {
        return this.teams;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        List<ApiTeam> _teams = new ArrayList<ApiTeam>();
        for (int i = 0; i < values.getRepeatedCount(1); i++) {
            _teams.add(new ApiTeam());
        }
        this.teams = values.getRepeatedObj(1, _teams);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRepeatedObj(1, this.teams);
    }

    @Override
    public String toString() {
        String res = "response TeamsList{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
