package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseCreateNewKeyGroup extends Response {

    public static final int HEADER = 0xa32;

    public static ResponseCreateNewKeyGroup fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseCreateNewKeyGroup(), data);
    }

    private int keyGroupId;

    public ResponseCreateNewKeyGroup(int keyGroupId) {
        this.keyGroupId = keyGroupId;
    }

    public ResponseCreateNewKeyGroup() {

    }

    public int getKeyGroupId() {
        return this.keyGroupId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.keyGroupId = values.getInt(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.keyGroupId);
    }

    @Override
    public String toString() {
        String res = "tuple CreateNewKeyGroup{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
