package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import im.actor.core.api.ApiEncryptionKeyGroup;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponsePublicKeyGroups extends Response {

    public static final int HEADER = 0xa2c;

    public static ResponsePublicKeyGroups fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponsePublicKeyGroups(), data);
    }

    private List<ApiEncryptionKeyGroup> publicKeyGroups;

    public ResponsePublicKeyGroups(@NotNull List<ApiEncryptionKeyGroup> publicKeyGroups) {
        this.publicKeyGroups = publicKeyGroups;
    }

    public ResponsePublicKeyGroups() {

    }

    @NotNull
    public List<ApiEncryptionKeyGroup> getPublicKeyGroups() {
        return this.publicKeyGroups;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        List<ApiEncryptionKeyGroup> _publicKeyGroups = new ArrayList<ApiEncryptionKeyGroup>();
        for (int i = 0; i < values.getRepeatedCount(1); i++) {
            _publicKeyGroups.add(new ApiEncryptionKeyGroup());
        }
        this.publicKeyGroups = values.getRepeatedObj(1, _publicKeyGroups);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRepeatedObj(1, this.publicKeyGroups);
    }

    @Override
    public String toString() {
        String res = "response PublicKeyGroups{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
