package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiTeam;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseCreateTeam extends Response {

    public static final int HEADER = 0xa07;

    public static ResponseCreateTeam fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseCreateTeam(), data);
    }

    private ApiTeam createdTeam;

    public ResponseCreateTeam(@NotNull ApiTeam createdTeam) {
        this.createdTeam = createdTeam;
    }

    public ResponseCreateTeam() {

    }

    @NotNull
    public ApiTeam getCreatedTeam() {
        return this.createdTeam;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.createdTeam = values.getObj(1, new ApiTeam());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.createdTeam == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.createdTeam);
    }

    @Override
    public String toString() {
        String res = "tuple CreateTeam{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
