package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseOptimizeSDP extends Response {

    public static final int HEADER = 0xa7e;

    public static ResponseOptimizeSDP fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseOptimizeSDP(), data);
    }

    private String optimizedSDP;

    public ResponseOptimizeSDP(@NotNull String optimizedSDP) {
        this.optimizedSDP = optimizedSDP;
    }

    public ResponseOptimizeSDP() {

    }

    @NotNull
    public String getOptimizedSDP() {
        return this.optimizedSDP;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.optimizedSDP = values.getString(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.optimizedSDP == null) {
            throw new IOException();
        }
        writer.writeString(1, this.optimizedSDP);
    }

    @Override
    public String toString() {
        String res = "tuple OptimizeSDP{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
