package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import im.actor.core.api.ApiGroup;
import im.actor.core.api.ApiUser;
import im.actor.core.api.ApiUserOutPeer;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseJoinGroup extends Response {

    public static final int HEADER = 0xb5;

    public static ResponseJoinGroup fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseJoinGroup(), data);
    }

    private ApiGroup group;
    private List<ApiUser> users;
    private List<ApiUserOutPeer> userPeers;
    private long rid;
    private int seq;
    private byte[] state;
    private long date;

    public ResponseJoinGroup(@NotNull ApiGroup group, @NotNull List<ApiUser> users, @NotNull List<ApiUserOutPeer> userPeers, long rid, int seq, @NotNull byte[] state, long date) {
        this.group = group;
        this.users = users;
        this.userPeers = userPeers;
        this.rid = rid;
        this.seq = seq;
        this.state = state;
        this.date = date;
    }

    public ResponseJoinGroup() {

    }

    @NotNull
    public ApiGroup getGroup() {
        return this.group;
    }

    @NotNull
    public List<ApiUser> getUsers() {
        return this.users;
    }

    @NotNull
    public List<ApiUserOutPeer> getUserPeers() {
        return this.userPeers;
    }

    public long getRid() {
        return this.rid;
    }

    public int getSeq() {
        return this.seq;
    }

    @NotNull
    public byte[] getState() {
        return this.state;
    }

    public long getDate() {
        return this.date;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.group = values.getObj(1, new ApiGroup());
        List<ApiUser> _users = new ArrayList<ApiUser>();
        for (int i = 0; i < values.getRepeatedCount(5); i++) {
            _users.add(new ApiUser());
        }
        this.users = values.getRepeatedObj(5, _users);
        List<ApiUserOutPeer> _userPeers = new ArrayList<ApiUserOutPeer>();
        for (int i = 0; i < values.getRepeatedCount(7); i++) {
            _userPeers.add(new ApiUserOutPeer());
        }
        this.userPeers = values.getRepeatedObj(7, _userPeers);
        this.rid = values.getLong(6);
        this.seq = values.getInt(2);
        this.state = values.getBytes(3);
        this.date = values.getLong(4);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.group == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.group);
        writer.writeRepeatedObj(5, this.users);
        writer.writeRepeatedObj(7, this.userPeers);
        writer.writeLong(6, this.rid);
        writer.writeInt(2, this.seq);
        if (this.state == null) {
            throw new IOException();
        }
        writer.writeBytes(3, this.state);
        writer.writeLong(4, this.date);
    }

    @Override
    public String toString() {
        String res = "tuple JoinGroup{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
