package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiMapValue;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseCompleteWebaction extends Response {

    public static final int HEADER = 0x7c;

    public static ResponseCompleteWebaction fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseCompleteWebaction(), data);
    }

    private ApiMapValue result;

    public ResponseCompleteWebaction(@NotNull ApiMapValue result) {
        this.result = result;
    }

    public ResponseCompleteWebaction() {

    }

    @NotNull
    public ApiMapValue getResult() {
        return this.result;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.result = values.getObj(1, new ApiMapValue());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.result == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.result);
    }

    @Override
    public String toString() {
        String res = "tuple CompleteWebaction{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
