package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import im.actor.core.api.ApiStickerCollection;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseLoadOwnStickers extends Response {

    public static final int HEADER = 0xef;

    public static ResponseLoadOwnStickers fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseLoadOwnStickers(), data);
    }

    private List<ApiStickerCollection> ownStickers;

    public ResponseLoadOwnStickers(@NotNull List<ApiStickerCollection> ownStickers) {
        this.ownStickers = ownStickers;
    }

    public ResponseLoadOwnStickers() {

    }

    @NotNull
    public List<ApiStickerCollection> getOwnStickers() {
        return this.ownStickers;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        List<ApiStickerCollection> _ownStickers = new ArrayList<ApiStickerCollection>();
        for (int i = 0; i < values.getRepeatedCount(1); i++) {
            _ownStickers.add(new ApiStickerCollection());
        }
        this.ownStickers = values.getRepeatedObj(1, _ownStickers);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRepeatedObj(1, this.ownStickers);
    }

    @Override
    public String toString() {
        String res = "tuple LoadOwnStickers{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
