package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiStickerCollection;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseLoadStickerCollection extends Response {

    public static final int HEADER = 0xf7;

    public static ResponseLoadStickerCollection fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseLoadStickerCollection(), data);
    }

    private ApiStickerCollection collection;

    public ResponseLoadStickerCollection(@NotNull ApiStickerCollection collection) {
        this.collection = collection;
    }

    public ResponseLoadStickerCollection() {

    }

    @NotNull
    public ApiStickerCollection getCollection() {
        return this.collection;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.collection = values.getObj(1, new ApiStickerCollection());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.collection == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.collection);
    }

    @Override
    public String toString() {
        String res = "tuple LoadStickerCollection{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
