package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.Nullable;

import java.io.IOException;

import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseJoinEventBus extends Response {

    public static final int HEADER = 0xa6d;

    public static ResponseJoinEventBus fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseJoinEventBus(), data);
    }

    private long deviceId;
    private byte[] rejoinToken;

    public ResponseJoinEventBus(long deviceId, @Nullable byte[] rejoinToken) {
        this.deviceId = deviceId;
        this.rejoinToken = rejoinToken;
    }

    public ResponseJoinEventBus() {

    }

    public long getDeviceId() {
        return this.deviceId;
    }

    @Nullable
    public byte[] getRejoinToken() {
        return this.rejoinToken;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.deviceId = values.getLong(1);
        this.rejoinToken = values.optBytes(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.deviceId);
        if (this.rejoinToken != null) {
            writer.writeBytes(2, this.rejoinToken);
        }
    }

    @Override
    public String toString() {
        String res = "tuple JoinEventBus{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
