package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseStartUsernameAuth extends Response {

    public static final int HEADER = 0xa0c;

    public static ResponseStartUsernameAuth fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseStartUsernameAuth(), data);
    }

    private String transactionHash;
    private boolean isRegistered;

    public ResponseStartUsernameAuth(@NotNull String transactionHash, boolean isRegistered) {
        this.transactionHash = transactionHash;
        this.isRegistered = isRegistered;
    }

    public ResponseStartUsernameAuth() {

    }

    @NotNull
    public String getTransactionHash() {
        return this.transactionHash;
    }

    public boolean isRegistered() {
        return this.isRegistered;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.transactionHash = values.getString(1);
        this.isRegistered = values.getBool(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.transactionHash == null) {
            throw new IOException();
        }
        writer.writeString(1, this.transactionHash);
        writer.writeBool(2, this.isRegistered);
    }

    @Override
    public String toString() {
        String res = "tuple StartUsernameAuth{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
