package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiGroupPre;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseCreateGroupPre extends Response {

    public static final int HEADER = 0x15;
    public static ResponseCreateGroupPre fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseCreateGroupPre(), data);
    }

    private int seq;
    private byte[] state;
    private long date;
    private ApiGroupPre groupPre;

    public ResponseCreateGroupPre(int seq, @NotNull byte[] state, long date, @NotNull ApiGroupPre groupPre) {
        this.seq = seq;
        this.state = state;
        this.date = date;
        this.groupPre = groupPre;
    }

    public ResponseCreateGroupPre() {

    }

    public int getSeq() {
        return this.seq;
    }

    @NotNull
    public byte[] getState() {
        return this.state;
    }

    public long getDate() {
        return this.date;
    }

    @NotNull
    public ApiGroupPre getGroupPre() {
        return this.groupPre;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.seq = values.getInt(1);
        this.state = values.getBytes(2);
        this.date = values.getLong(3);
        this.groupPre = values.getObj(4, new ApiGroupPre());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.seq);
        if (this.state == null) {
            throw new IOException();
        }
        writer.writeBytes(2, this.state);
        writer.writeLong(3, this.date);
        if (this.groupPre == null) {
            throw new IOException();
        }
        writer.writeObject(4, this.groupPre);
    }

    @Override
    public String toString() {
        String res = "tuple CreateGroupPre{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
