package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdatePauseNotifications extends Update {

    public static final int HEADER = 0xa6;

    public static UpdatePauseNotifications fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdatePauseNotifications(), data);
    }

    private int timeout;

    public UpdatePauseNotifications(int timeout) {
        this.timeout = timeout;
    }

    public UpdatePauseNotifications() {

    }

    public int getTimeout() {
        return this.timeout;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.timeout = values.getInt(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.timeout);
    }

    @Override
    public String toString() {
        String res = "update PauseNotifications{";
        res += "timeout=" + this.timeout;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
