package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateUserBlocked extends Update {

    public static final int HEADER = 0xa45;

    public static UpdateUserBlocked fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateUserBlocked(), data);
    }

    private int uid;

    public UpdateUserBlocked(int uid) {
        this.uid = uid;
    }

    public UpdateUserBlocked() {

    }

    public int getUid() {
        return this.uid;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.uid = values.getInt(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.uid);
    }

    @Override
    public String toString() {
        String res = "update UserBlocked{";
        res += "uid=" + this.uid;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
