package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateGroupOwnerChanged extends Update {

    public static final int HEADER = 0xa3b;

    public static UpdateGroupOwnerChanged fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateGroupOwnerChanged(), data);
    }

    private int groupId;
    private int userId;

    public UpdateGroupOwnerChanged(int groupId, int userId) {
        this.groupId = groupId;
        this.userId = userId;
    }

    public UpdateGroupOwnerChanged() {

    }

    public int getGroupId() {
        return this.groupId;
    }

    public int getUserId() {
        return this.userId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupId = values.getInt(1);
        this.userId = values.getInt(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.groupId);
        writer.writeInt(2, this.userId);
    }

    @Override
    public String toString() {
        String res = "update GroupOwnerChanged{";
        res += "groupId=" + this.groupId;
        res += ", userId=" + this.userId;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
