package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiPeer;
import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateChatArchive extends Update {

    public static final int HEADER = 0x5e;

    public static UpdateChatArchive fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateChatArchive(), data);
    }

    private ApiPeer peer;

    public UpdateChatArchive(@NotNull ApiPeer peer) {
        this.peer = peer;
    }

    public UpdateChatArchive() {

    }

    @NotNull
    public ApiPeer getPeer() {
        return this.peer;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.peer = values.getObj(1, new ApiPeer());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.peer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.peer);
    }

    @Override
    public String toString() {
        String res = "update ChatArchive{";
        res += "peer=" + this.peer;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
