package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.Nullable;

import java.io.IOException;

import im.actor.core.api.ApiMapValue;
import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateUserFullExtChanged extends Update {

    public static final int HEADER = 0xdb;

    public static UpdateUserFullExtChanged fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateUserFullExtChanged(), data);
    }

    private int uid;
    private ApiMapValue ext;

    public UpdateUserFullExtChanged(int uid, @Nullable ApiMapValue ext) {
        this.uid = uid;
        this.ext = ext;
    }

    public UpdateUserFullExtChanged() {

    }

    public int getUid() {
        return this.uid;
    }

    @Nullable
    public ApiMapValue getExt() {
        return this.ext;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.uid = values.getInt(1);
        this.ext = values.optObj(3, new ApiMapValue());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.uid);
        if (this.ext != null) {
            writer.writeObject(3, this.ext);
        }
    }

    @Override
    public String toString() {
        String res = "update UserFullExtChanged{";
        res += "uid=" + this.uid;
        res += ", ext=" + this.ext;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
