package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateGroupMemberChanged extends Update {

    public static final int HEADER = 0xa34;

    public static UpdateGroupMemberChanged fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateGroupMemberChanged(), data);
    }

    private int groupId;
    private boolean isMember;

    public UpdateGroupMemberChanged(int groupId, boolean isMember) {
        this.groupId = groupId;
        this.isMember = isMember;
    }

    public UpdateGroupMemberChanged() {

    }

    public int getGroupId() {
        return this.groupId;
    }

    public boolean isMember() {
        return this.isMember;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupId = values.getInt(1);
        this.isMember = values.getBool(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.groupId);
        writer.writeBool(2, this.isMember);
    }

    @Override
    public String toString() {
        String res = "update GroupMemberChanged{";
        res += "groupId=" + this.groupId;
        res += ", isMember=" + this.isMember;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
