package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.Nullable;

import java.io.IOException;

import im.actor.core.api.ApiMapValue;
import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateGroupFullExtChanged extends Update {

    public static final int HEADER = 0xa3a;

    public static UpdateGroupFullExtChanged fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateGroupFullExtChanged(), data);
    }

    private int groupId;
    private ApiMapValue ext;

    public UpdateGroupFullExtChanged(int groupId, @Nullable ApiMapValue ext) {
        this.groupId = groupId;
        this.ext = ext;
    }

    public UpdateGroupFullExtChanged() {

    }

    public int getGroupId() {
        return this.groupId;
    }

    @Nullable
    public ApiMapValue getExt() {
        return this.ext;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupId = values.getInt(1);
        this.ext = values.optObj(2, new ApiMapValue());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.groupId);
        if (this.ext != null) {
            writer.writeObject(2, this.ext);
        }
    }

    @Override
    public String toString() {
        String res = "update GroupFullExtChanged{";
        res += "groupId=" + this.groupId;
        res += ", ext=" + this.ext;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
