package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateCallUpgraded extends Update {

    public static final int HEADER = 0x38;

    public static UpdateCallUpgraded fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateCallUpgraded(), data);
    }

    private long callId;
    private int groupId;

    public UpdateCallUpgraded(long callId, int groupId) {
        this.callId = callId;
        this.groupId = groupId;
    }

    public UpdateCallUpgraded() {

    }

    public long getCallId() {
        return this.callId;
    }

    public int getGroupId() {
        return this.groupId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.callId = values.getLong(1);
        this.groupId = values.getInt(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.callId);
        writer.writeInt(2, this.groupId);
    }

    @Override
    public String toString() {
        String res = "update CallUpgraded{";
        res += "callId=" + this.callId;
        res += ", groupId=" + this.groupId;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
