package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdatePublicKeyGroupRemoved extends Update {

    public static final int HEADER = 0x69;

    public static UpdatePublicKeyGroupRemoved fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdatePublicKeyGroupRemoved(), data);
    }

    private int uid;
    private int keyGroupId;

    public UpdatePublicKeyGroupRemoved(int uid, int keyGroupId) {
        this.uid = uid;
        this.keyGroupId = keyGroupId;
    }

    public UpdatePublicKeyGroupRemoved() {

    }

    public int getUid() {
        return this.uid;
    }

    public int getKeyGroupId() {
        return this.keyGroupId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.uid = values.getInt(1);
        this.keyGroupId = values.getInt(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.uid);
        writer.writeInt(2, this.keyGroupId);
    }

    @Override
    public String toString() {
        String res = "update PublicKeyGroupRemoved{";
        res += "uid=" + this.uid;
        res += ", keyGroupId=" + this.keyGroupId;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
