package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateGroupMemberAdminChanged extends Update {

    public static final int HEADER = 0xa43;

    public static UpdateGroupMemberAdminChanged fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateGroupMemberAdminChanged(), data);
    }

    private int groupId;
    private int userId;
    private boolean isAdmin;

    public UpdateGroupMemberAdminChanged(int groupId, int userId, boolean isAdmin) {
        this.groupId = groupId;
        this.userId = userId;
        this.isAdmin = isAdmin;
    }

    public UpdateGroupMemberAdminChanged() {

    }

    public int getGroupId() {
        return this.groupId;
    }

    public int getUserId() {
        return this.userId;
    }

    public boolean isAdmin() {
        return this.isAdmin;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupId = values.getInt(1);
        this.userId = values.getInt(2);
        this.isAdmin = values.getBool(3);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.groupId);
        writer.writeInt(2, this.userId);
        writer.writeBool(3, this.isAdmin);
    }

    @Override
    public String toString() {
        String res = "update GroupMemberAdminChanged{";
        res += "groupId=" + this.groupId;
        res += ", userId=" + this.userId;
        res += ", isAdmin=" + this.isAdmin;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
