package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;

import im.actor.core.api.ApiPeer;
import im.actor.core.api.ApiQuotedMessage;
import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateMessageQuotedChanged extends Update {

    public static final int HEADER = 0xa9;

    public static UpdateMessageQuotedChanged fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateMessageQuotedChanged(), data);
    }

    private ApiPeer peer;
    private long rid;
    private ApiQuotedMessage quotedMessage;

    public UpdateMessageQuotedChanged(@NotNull ApiPeer peer, long rid, @Nullable ApiQuotedMessage quotedMessage) {
        this.peer = peer;
        this.rid = rid;
        this.quotedMessage = quotedMessage;
    }

    public UpdateMessageQuotedChanged() {

    }

    @NotNull
    public ApiPeer getPeer() {
        return this.peer;
    }

    public long getRid() {
        return this.rid;
    }

    @Nullable
    public ApiQuotedMessage getQuotedMessage() {
        return this.quotedMessage;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.peer = values.getObj(1, new ApiPeer());
        this.rid = values.getLong(2);
        this.quotedMessage = values.optObj(3, new ApiQuotedMessage());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.peer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.peer);
        writer.writeLong(2, this.rid);
        if (this.quotedMessage != null) {
            writer.writeObject(3, this.quotedMessage);
        }
    }

    @Override
    public String toString() {
        String res = "update MessageQuotedChanged{";
        res += "peer=" + this.peer;
        res += ", rid=" + this.rid;
        res += ", quotedMessage=" + this.quotedMessage;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
