package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.Nullable;

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateCallHandled extends Update {

    public static final int HEADER = 0x35;

    public static UpdateCallHandled fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateCallHandled(), data);
    }

    private long callId;
    private Integer attemptIndex;

    public UpdateCallHandled(long callId, @Nullable Integer attemptIndex) {
        this.callId = callId;
        this.attemptIndex = attemptIndex;
    }

    public UpdateCallHandled() {

    }

    public long getCallId() {
        return this.callId;
    }

    @Nullable
    public Integer getAttemptIndex() {
        return this.attemptIndex;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.callId = values.getLong(1);
        this.attemptIndex = values.optInt(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.callId);
        if (this.attemptIndex != null) {
            writer.writeInt(2, this.attemptIndex);
        }
    }

    @Override
    public String toString() {
        String res = "update CallHandled{";
        res += "callId=" + this.callId;
        res += ", attemptIndex=" + this.attemptIndex;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
