package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiGroupPre;
import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateGroupPreCreated extends Update {

    public static final int HEADER = 0x14;
    public static UpdateGroupPreCreated fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateGroupPreCreated(), data);
    }

    private ApiGroupPre groupPre;

    public UpdateGroupPreCreated(@NotNull ApiGroupPre groupPre) {
        this.groupPre = groupPre;
    }

    public UpdateGroupPreCreated() {

    }

    @NotNull
    public ApiGroupPre getGroupPre() {
        return this.groupPre;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupPre = values.getObj(1, new ApiGroupPre());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.groupPre == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.groupPre);
    }

    @Override
    public String toString() {
        String res = "update GroupPreCreated{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
