package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateEventBusDisposed extends Update {

    public static final int HEADER = 0xa04;

    public static UpdateEventBusDisposed fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateEventBusDisposed(), data);
    }

    private String id;

    public UpdateEventBusDisposed(@NotNull String id) {
        this.id = id;
    }

    public UpdateEventBusDisposed() {

    }

    @NotNull
    public String getId() {
        return this.id;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.id = values.getString(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.id == null) {
            throw new IOException();
        }
        writer.writeString(1, this.id);
    }

    @Override
    public String toString() {
        String res = "update EventBusDisposed{";
        res += "id=" + this.id;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
