package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateEventBusDeviceConnected extends Update {

    public static final int HEADER = 0xa01;

    public static UpdateEventBusDeviceConnected fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateEventBusDeviceConnected(), data);
    }

    private String id;
    private Integer userId;
    private long deviceId;

    public UpdateEventBusDeviceConnected(@NotNull String id, @Nullable Integer userId, long deviceId) {
        this.id = id;
        this.userId = userId;
        this.deviceId = deviceId;
    }

    public UpdateEventBusDeviceConnected() {

    }

    @NotNull
    public String getId() {
        return this.id;
    }

    @Nullable
    public Integer getUserId() {
        return this.userId;
    }

    public long getDeviceId() {
        return this.deviceId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.id = values.getString(1);
        this.userId = values.optInt(2);
        this.deviceId = values.getLong(3);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.id == null) {
            throw new IOException();
        }
        writer.writeString(1, this.id);
        if (this.userId != null) {
            writer.writeInt(2, this.userId);
        }
        writer.writeLong(3, this.deviceId);
    }

    @Override
    public String toString() {
        String res = "update EventBusDeviceConnected{";
        res += "id=" + this.id;
        res += ", userId=" + this.userId;
        res += ", deviceId=" + this.deviceId;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
