package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;
import im.actor.runtime.collections.SparseArray;

import static im.actor.runtime.bser.Utils.byteArrayToStringCompact;

public class ApiBinaryMessage extends ApiMessage {

    private String contentTag;
    private byte[] msg;

    public ApiBinaryMessage(@NotNull String contentTag, @NotNull byte[] msg) {
        this.contentTag = contentTag;
        this.msg = msg;
    }

    public ApiBinaryMessage() {

    }

    public int getHeader() {
        return 7;
    }

    @NotNull
    public String getContentTag() {
        return this.contentTag;
    }

    @NotNull
    public byte[] getMsg() {
        return this.msg;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.contentTag = values.getString(1);
        this.msg = values.getBytes(2);
        if (values.hasRemaining()) {
            setUnmappedObjects(values.buildRemaining());
        }
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.contentTag == null) {
            throw new IOException();
        }
        writer.writeString(1, this.contentTag);
        if (this.msg == null) {
            throw new IOException();
        }
        writer.writeBytes(2, this.msg);
        if (this.getUnmappedObjects() != null) {
            SparseArray<Object> unmapped = this.getUnmappedObjects();
            for (int i = 0; i < unmapped.size(); i++) {
                int key = unmapped.keyAt(i);
                writer.writeUnmapped(key, unmapped.get(key));
            }
        }
    }

    @Override
    public String toString() {
        String res = "struct BinaryMessage{";
        res += "contentTag=" + this.contentTag;
        res += ", msg=" + byteArrayToStringCompact(this.msg);
        res += "}";
        return res;
    }

}
