package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

public enum ApiDocsHistoryType {

    PHOTO(1),
    VIDEO(2),
    DOCUMENT(3),
    UNSUPPORTED_VALUE(-1);

    private int value;

    ApiDocsHistoryType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static ApiDocsHistoryType parse(int value) throws IOException {
        switch (value) {
            case 1:
                return ApiDocsHistoryType.PHOTO;
            case 2:
                return ApiDocsHistoryType.VIDEO;
            case 3:
                return ApiDocsHistoryType.DOCUMENT;
            default:
                return ApiDocsHistoryType.UNSUPPORTED_VALUE;
        }
    }
}
