package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiDoubleValue extends ApiRawValue {

    private double value;

    public ApiDoubleValue(double value) {
        this.value = value;
    }

    public ApiDoubleValue() {

    }

    public int getHeader() {
        return 4;
    }

    public double getValue() {
        return this.value;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.value = values.getDouble(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeDouble(1, this.value);
    }

    @Override
    public String toString() {
        String res = "struct DoubleValue{";
        res += "}";
        return res;
    }

}
