package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.runtime.bser.BserObject;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

import static im.actor.runtime.bser.Utils.byteArrayToString;

public class ApiEncryptedBoxSignature extends BserObject {

    private String algType;
    private byte[] signature;

    public ApiEncryptedBoxSignature(@NotNull String algType, @NotNull byte[] signature) {
        this.algType = algType;
        this.signature = signature;
    }

    public ApiEncryptedBoxSignature() {

    }

    @NotNull
    public String getAlgType() {
        return this.algType;
    }

    @NotNull
    public byte[] getSignature() {
        return this.signature;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.algType = values.getString(1);
        this.signature = values.getBytes(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.algType == null) {
            throw new IOException();
        }
        writer.writeString(1, this.algType);
        if (this.signature == null) {
            throw new IOException();
        }
        writer.writeBytes(2, this.signature);
    }

    @Override
    public String toString() {
        String res = "struct EncryptedBoxSignature{";
        res += "algType=" + this.algType;
        res += ", signature=" + byteArrayToString(this.signature);
        res += "}";
        return res;
    }

}
