package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.runtime.bser.BserObject;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiEventRecord extends BserObject {

    private long date;
    private ApiEvent event;

    public ApiEventRecord(long date, @NotNull ApiEvent event) {
        this.date = date;
        this.event = event;
    }

    public ApiEventRecord() {

    }

    public long getDate() {
        return this.date;
    }

    @NotNull
    public ApiEvent getEvent() {
        return this.event;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.date = values.getLong(1);
        this.event = ApiEvent.fromBytes(values.getBytes(2));
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.date);
        if (this.event == null) {
            throw new IOException();
        }

        writer.writeBytes(2, this.event.buildContainer());
    }

    @Override
    public String toString() {
        String res = "struct EventRecord{";
        res += "}";
        return res;
    }

}
