package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

public enum ApiGroupPreType {

    GROUP(1),
    CHANNEL(2),
    UNSUPPORTED_VALUE(-1);

    private int value;

    ApiGroupPreType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static ApiGroupPreType parse(int value) throws IOException {
        switch(value) {
            case 1: return ApiGroupPreType.GROUP;
            case 2: return ApiGroupPreType.CHANNEL;
            default: return ApiGroupPreType.UNSUPPORTED_VALUE;
        }
    }
}
