package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiInt32Value extends ApiRawValue {

    private int value;

    public ApiInt32Value(int value) {
        this.value = value;
    }

    public ApiInt32Value() {

    }

    public int getHeader() {
        return 2;
    }

    public int getValue() {
        return this.value;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.value = values.getInt(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.value);
    }

    @Override
    public String toString() {
        String res = "struct Int32Value{";
        res += "}";
        return res;
    }

}
