package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.runtime.bser.BserObject;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiKeyGroupId extends BserObject {

    private int uid;
    private int keyGroupId;

    public ApiKeyGroupId(int uid, int keyGroupId) {
        this.uid = uid;
        this.keyGroupId = keyGroupId;
    }

    public ApiKeyGroupId() {

    }

    public int getUid() {
        return this.uid;
    }

    public int getKeyGroupId() {
        return this.keyGroupId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.uid = values.getInt(1);
        this.keyGroupId = values.getInt(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.uid);
        writer.writeInt(2, this.keyGroupId);
    }

    @Override
    public String toString() {
        String res = "struct KeyGroupId{";
        res += "uid=" + this.uid;
        res += ", keyGroupId=" + this.keyGroupId;
        res += "}";
        return res;
    }

}
