package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.List;

import im.actor.runtime.bser.BserObject;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiMessageReaction extends BserObject {

    private List<Integer> users;
    private String code;

    public ApiMessageReaction(@NotNull List<Integer> users, @NotNull String code) {
        this.users = users;
        this.code = code;
    }

    public ApiMessageReaction() {

    }

    @NotNull
    public List<Integer> getUsers() {
        return this.users;
    }

    @NotNull
    public String getCode() {
        return this.code;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.users = values.getRepeatedInt(1);
        this.code = values.getString(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRepeatedInt(1, this.users);
        if (this.code == null) {
            throw new IOException();
        }
        writer.writeString(2, this.code);
    }

    @Override
    public String toString() {
        String res = "struct MessageReaction{";
        res += "users=" + this.users;
        res += ", code=" + this.code;
        res += "}";
        return res;
    }

}
