package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiMessageUnsupported extends ApiMessage {

    private int key;
    private byte[] content;

    public ApiMessageUnsupported(int key, byte[] content) {
        this.key = key;
        this.content = content;
    }

    @Override
    public int getHeader() {
        return this.key;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        throw new IOException("Parsing is unsupported");
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRaw(content);
    }

}
