package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.runtime.bser.BserObject;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiMessageOutReference extends BserObject {

    private ApiOutPeer peer;
    private long rid;

    public ApiMessageOutReference(@NotNull ApiOutPeer peer, long rid) {
        this.peer = peer;
        this.rid = rid;
    }

    public ApiMessageOutReference() {

    }

    @NotNull
    public ApiOutPeer getPeer() {
        return this.peer;
    }

    public long getRid() {
        return this.rid;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.peer = values.getObj(1, new ApiOutPeer());
        this.rid = values.getLong(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.peer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.peer);
        writer.writeLong(2, this.rid);
    }

    @Override
    public String toString() {
        String res = "struct MessageOutReference{";
        res += "peer=" + this.peer;
        res += ", rid=" + this.rid;
        res += "}";
        return res;
    }

}
