package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiNeedDisconnect extends ApiWebRTCSignaling {

    private long device;

    public ApiNeedDisconnect(long device) {
        this.device = device;
    }

    public ApiNeedDisconnect() {

    }

    public int getHeader() {
        return 20;
    }

    public long getDevice() {
        return this.device;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.device = values.getLong(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.device);
    }

    @Override
    public String toString() {
        String res = "struct NeedDisconnect{";
        res += "}";
        return res;
    }

}
