package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.runtime.bser.BserObject;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiOutTeam extends BserObject {

    private int id;
    private long accessHash;

    public ApiOutTeam(int id, long accessHash) {
        this.id = id;
        this.accessHash = accessHash;
    }

    public ApiOutTeam() {

    }

    public int getId() {
        return this.id;
    }

    public long getAccessHash() {
        return this.accessHash;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.id = values.getInt(1);
        this.accessHash = values.getLong(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.id);
        writer.writeLong(2, this.accessHash);
    }

    @Override
    public String toString() {
        String res = "struct OutTeam{";
        res += "id=" + this.id;
        res += ", accessHash=" + this.accessHash;
        res += "}";
        return res;
    }

}
