package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiOnRenegotiationNeeded extends ApiWebRTCSignaling {

    private long device;
    private long sessionId;

    public ApiOnRenegotiationNeeded(long device, long sessionId) {
        this.device = device;
        this.sessionId = sessionId;
    }

    public ApiOnRenegotiationNeeded() {

    }

    public int getHeader() {
        return 25;
    }

    public long getDevice() {
        return this.device;
    }

    public long getSessionId() {
        return this.sessionId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.device = values.getLong(1);
        this.sessionId = values.getLong(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.device);
        writer.writeLong(2, this.sessionId);
    }

    @Override
    public String toString() {
        String res = "struct OnRenegotiationNeeded{";
        res += "device=" + this.device;
        res += ", sessionId=" + this.sessionId;
        res += "}";
        return res;
    }

}
