package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;
import im.actor.runtime.collections.SparseArray;

public class ApiPredefinedColor extends ApiColor {

    private ApiColors color;

    public ApiPredefinedColor(@NotNull ApiColors color) {
        this.color = color;
    }

    public ApiPredefinedColor() {

    }

    public int getHeader() {
        return 2;
    }

    @NotNull
    public ApiColors getColor() {
        return this.color;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.color = ApiColors.parse(values.getInt(1));
        if (values.hasRemaining()) {
            setUnmappedObjects(values.buildRemaining());
        }
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.color == null) {
            throw new IOException();
        }
        writer.writeInt(1, this.color.getValue());
        if (this.getUnmappedObjects() != null) {
            SparseArray<Object> unmapped = this.getUnmappedObjects();
            for (int i = 0; i < unmapped.size(); i++) {
                int key = unmapped.keyAt(i);
                writer.writeUnmapped(key, unmapped.get(key));
            }
        }
    }

    @Override
    public String toString() {
        String res = "struct PredefinedColor{";
        res += "}";
        return res;
    }

}
