package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;
import im.actor.runtime.collections.SparseArray;

public class ApiRgbColor extends ApiColor {

    private int rgb;

    public ApiRgbColor(int rgb) {
        this.rgb = rgb;
    }

    public ApiRgbColor() {

    }

    public int getHeader() {
        return 1;
    }

    public int getRgb() {
        return this.rgb;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.rgb = values.getInt(1);
        if (values.hasRemaining()) {
            setUnmappedObjects(values.buildRemaining());
        }
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.rgb);
        if (this.getUnmappedObjects() != null) {
            SparseArray<Object> unmapped = this.getUnmappedObjects();
            for (int i = 0; i < unmapped.size(); i++) {
                int key = unmapped.keyAt(i);
                writer.writeUnmapped(key, unmapped.get(key));
            }
        }
    }

    @Override
    public String toString() {
        String res = "struct RgbColor{";
        res += "rgb=" + this.rgb;
        res += "}";
        return res;
    }

}
