package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.Nullable;

import java.io.IOException;

import im.actor.runtime.bser.BserObject;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiSyncedValue extends BserObject {

    private long id;
    private byte[] value;

    public ApiSyncedValue(long id, @Nullable byte[] value) {
        this.id = id;
        this.value = value;
    }

    public ApiSyncedValue() {

    }

    public long getId() {
        return this.id;
    }

    @Nullable
    public byte[] getValue() {
        return this.value;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.id = values.getLong(1);
        this.value = values.optBytes(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.id);
        if (this.value != null) {
            writer.writeBytes(2, this.value);
        }
    }

    @Override
    public String toString() {
        String res = "struct SyncedValue{";
        res += "id=" + this.id;
        res += ", value=" + this.value;
        res += "}";
        return res;
    }

}
