package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;
import im.actor.runtime.collections.SparseArray;

public class ApiSurveyMessage extends ApiMessage {

    private long surveyId;

    public ApiSurveyMessage(long surveyId) {
        this.surveyId = surveyId;
    }

    public ApiSurveyMessage() {

    }

    public int getHeader() {
        return 35;
    }

    public long getSurveyId() {
        return this.surveyId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.surveyId = values.getLong(1);
        if (values.hasRemaining()) {
            setUnmappedObjects(values.buildRemaining());
        }
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.surveyId);
        if (this.getUnmappedObjects() != null) {
            SparseArray<Object> unmapped = this.getUnmappedObjects();
            for (int i = 0; i < unmapped.size(); i++) {
                int key = unmapped.keyAt(i);
                writer.writeUnmapped(key, unmapped.get(key));
            }
        }
    }

    @Override
    public String toString() {
        String res = "struct SurveyMessage{";
        res += "}";
        return res;
    }

}
