package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;
import im.actor.runtime.collections.SparseArray;

public class ApiServiceExUserInvited extends ApiServiceEx {

    private int invitedUid;

    public ApiServiceExUserInvited(int invitedUid) {
        this.invitedUid = invitedUid;
    }

    public ApiServiceExUserInvited() {

    }

    public int getHeader() {
        return 1;
    }

    public int getInvitedUid() {
        return this.invitedUid;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.invitedUid = values.getInt(1);
        if (values.hasRemaining()) {
            setUnmappedObjects(values.buildRemaining());
        }
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.invitedUid);
        if (this.getUnmappedObjects() != null) {
            SparseArray<Object> unmapped = this.getUnmappedObjects();
            for (int i = 0; i < unmapped.size(); i++) {
                int key = unmapped.keyAt(i);
                writer.writeUnmapped(key, unmapped.get(key));
            }
        }
    }

    @Override
    public String toString() {
        String res = "struct ServiceExUserInvited{";
        res += "invitedUid=" + this.invitedUid;
        res += "}";
        return res;
    }

}
