package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ApiStringValue extends ApiRawValue {

    private String text;

    public ApiStringValue(@NotNull String text) {
        this.text = text;
    }

    public ApiStringValue() {

    }

    public int getHeader() {
        return 1;
    }

    @NotNull
    public String getText() {
        return this.text;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.text = values.getString(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.text == null) {
            throw new IOException();
        }
        writer.writeString(1, this.text);
    }

    @Override
    public String toString() {
        String res = "struct StringValue{";
        res += "}";
        return res;
    }

}
