package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;

public class ApiSurveyMessage extends ApiMessage {

    private long surveyId;

    public ApiSurveyMessage(long surveyId) {
        this.surveyId = surveyId;
    }

    public ApiSurveyMessage() {

    }

    public int getHeader() {
        return 35;
    }

    public long getSurveyId() {
        return this.surveyId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.surveyId = values.getLong(1);
        if (values.hasRemaining()) {
            setUnmappedObjects(values.buildRemaining());
        }
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.surveyId);
        if (this.getUnmappedObjects() != null) {
            SparseArray<Object> unmapped = this.getUnmappedObjects();
            for (int i = 0; i < unmapped.size(); i++) {
                int key = unmapped.keyAt(i);
                writer.writeUnmapped(key, unmapped.get(key));
            }
        }
    }

    @Override
    public String toString() {
        String res = "struct SurveyMessage{";
        res += "}";
        return res;
    }

}
