package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;
import im.actor.runtime.collections.SparseArray;

public class ApiTextExMarkdown extends ApiTextMessageEx {

    private String markdown;

    public ApiTextExMarkdown(@NotNull String markdown) {
        this.markdown = markdown;
    }

    public ApiTextExMarkdown() {

    }

    public int getHeader() {
        return 1;
    }

    @NotNull
    public String getMarkdown() {
        return this.markdown;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.markdown = values.getString(2);
        if (values.hasRemaining()) {
            setUnmappedObjects(values.buildRemaining());
        }
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.markdown == null) {
            throw new IOException();
        }
        writer.writeString(2, this.markdown);
        if (this.getUnmappedObjects() != null) {
            SparseArray<Object> unmapped = this.getUnmappedObjects();
            for (int i = 0; i < unmapped.size(); i++) {
                int key = unmapped.keyAt(i);
                writer.writeUnmapped(key, unmapped.get(key));
            }
        }
    }

    @Override
    public String toString() {
        String res = "struct TextExMarkdown{";
        res += "markdown=" + this.markdown;
        res += "}";
        return res;
    }

}
