package im.actor.core.api.base;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.RpcScope;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class SeqUpdateTooLong extends RpcScope {

    public static final int HEADER = 0x19;

    public static SeqUpdateTooLong fromBytes(byte[] data) throws IOException {
        return Bser.parse(new SeqUpdateTooLong(), data);
    }


    public SeqUpdateTooLong() {

    }

    @Override
    public void parse(BserValues values) throws IOException {
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
    }

    @Override
    public String toString() {
        String res = "update box SeqUpdateTooLong{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
